# Sample Prices

In [10]:
from mintalib.samples import sample_prices

FREQ = "hourly"

prices = sample_prices(FREQ)
print(prices.index.dtype)
prices

datetime64[ns, America/New_York]

,open,high,low,close,volume
datetime,,,,,
2022-10-24 09:30:00-04:00,147.250000,148.350006,146.000000,146.630203,20169319
2022-10-24 10:30:00-04:00,146.630096,148.449997,146.470001,148.210007,10131448
2022-10-24 11:30:00-04:00,148.219894,148.820007,147.529999,148.436096,7921370
2022-10-24 12:30:00-04:00,148.434998,148.729996,147.910004,148.080002,6399968
2022-10-24 13:30:00-04:00,148.070007,149.365005,147.929993,149.285004,5909741
...,...,...,...,...,...
2024-10-21 11:30:00-04:00,235.399994,236.604996,235.285004,236.279999,3915718
2024-10-21 12:30:00-04:00,236.300003,236.615005,236.113998,236.370102,2531558
2024-10-21 13:30:00-04:00,236.380005,236.850006,236.199997,236.225006,2198486
2024-10-21 14:30:00-04:00,236.229996,236.270004,235.889999,236.134995,2196498
2024-10-21 15:30:00-04:00,236.134995,236.580002,235.827499,236.580002,3275560

In [11]:
plprices = sample_prices(FREQ, backend="polars")
plprices

shape: (3_491, 6)
┌────────────────────────────────┬────────────┬────────────┬────────────┬────────────┬──────────┐
│ datetime                       ┆ open       ┆ high       ┆ low        ┆ close      ┆ volume   │
│ ---                            ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ datetime[ns, America/New_York] ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞════════════════════════════════╪════════════╪════════════╪════════════╪════════════╪══════════╡
│ 2022-10-24 09:30:00 EDT        ┆ 147.25     ┆ 148.350006 ┆ 146.0      ┆ 146.630203 ┆ 20169319 │
│ 2022-10-24 10:30:00 EDT        ┆ 146.630096 ┆ 148.449997 ┆ 146.470001 ┆ 148.210007 ┆ 10131448 │
│ 2022-10-24 11:30:00 EDT        ┆ 148.219894 ┆ 148.820007 ┆ 147.529999 ┆ 148.436096 ┆ 7921370  │
│ 2022-10-24 12:30:00 EDT        ┆ 148.434998 ┆ 148.729996 ┆ 147.910004 ┆ 148.080002 ┆ 6399968  │
│ 2022-10-24 13:30:00 EDT        ┆ 148.070007 ┆ 149.365005 ┆ 147.929993 ┆ 149.285004 ┆ 5909741  │
│ …                              ┆ …          ┆ …          ┆ …          ┆ …          ┆ …        │
│ 2024-10-21 11:30:00 EDT        ┆ 235.399994 ┆ 236.604996 ┆ 235.285004 ┆ 236.279999 ┆ 3915718  │
│ 2024-10-21 12:30:00 EDT        ┆ 236.300003 ┆ 236.615005 ┆ 236.113998 ┆ 236.370102 ┆ 2531558  │
│ 2024-10-21 13:30:00 EDT        ┆ 236.380005 ┆ 236.850006 ┆ 236.199997 ┆ 236.225006 ┆ 2198486  │
│ 2024-10-21 14:30:00 EDT        ┆ 236.229996 ┆ 236.270004 ┆ 235.889999 ┆ 236.134995 ┆ 2196498  │
│ 2024-10-21 15:30:00 EDT        ┆ 236.134995 ┆ 236.580002 ┆ 235.827499 ┆ 236.580002 ┆ 3275560  │
└────────────────────────────────┴────────────┴────────────┴────────────┴────────────┴──────────┘

In [12]:
prices = plprices.to_pandas().set_index("datetime")
print(prices.index.dtype)
prices

datetime64[ns, America/New_York]

,open,high,low,close,volume
datetime,,,,,
2022-10-24 09:30:00-04:00,147.250000,148.350006,146.000000,146.630203,20169319
2022-10-24 10:30:00-04:00,146.630096,148.449997,146.470001,148.210007,10131448
2022-10-24 11:30:00-04:00,148.219894,148.820007,147.529999,148.436096,7921370
2022-10-24 12:30:00-04:00,148.434998,148.729996,147.910004,148.080002,6399968
2022-10-24 13:30:00-04:00,148.070007,149.365005,147.929993,149.285004,5909741
...,...,...,...,...,...
2024-10-21 11:30:00-04:00,235.399994,236.604996,235.285004,236.279999,3915718
2024-10-21 12:30:00-04:00,236.300003,236.615005,236.113998,236.370102,2531558
2024-10-21 13:30:00-04:00,236.380005,236.850006,236.199997,236.225006,2198486
2024-10-21 14:30:00-04:00,236.229996,236.270004,235.889999,236.134995,2196498
2024-10-21 15:30:00-04:00,236.134995,236.580002,235.827499,236.580002,3275560