# Update `README.md`

Does two things:
1. Updates the "List of Indicators" table in the root `README.md`
2. Generates a PyPI-ready version of `README.md` with absolute URLs into `output/pypi-readme.md`

In [1]:
import re
import toml
import shutil
import posixpath

from pathlib import Path

import pandas as pd

from mintalib import core

In [2]:
ROOTDIR = Path.cwd().parent
PYPROJECT = ROOTDIR.joinpath("pyproject.toml").resolve(strict=True)

In [3]:
def jquery(data: dict, item: str, default=None):
    result = data

    for i in item.split("."):
        result = result.get(i, None)
        if result is None:
            return default

    return result


def get_project_url(pyproject=PYPROJECT):
    """extract project url from project configuration"""

    if not pyproject.exists():
        raise FileNotFoundError("pyproject.toml")

    config = toml.load(pyproject)
    
    return jquery(config, "project.urls.homepage")

get_project_url()

'https://github.com/furechan/mintalib'

In [4]:

def get_info(func):
    """information about function"""

    info = dict(Name=func.__name__)

    doc = func.__doc__ or ""
    description = doc.strip().partition("\n")[0]
    if description is not None:
        info.update(Description=description)

    return info


def list_indicators():
    """list indicators"""

    from mintalib import indicators

    result = [v for k, v in vars(indicators).items() if k.isupper() and callable(v)]

    result = [get_info(f) for f in result]

    result = pd.DataFrame(result).set_index("Name")

    result = result.sort_index()

    return result

list_indicators()

                                                Description
Name
ABS                                        calc_abs(series)
ADX                        calc_adx(prices, long period=14)
ALMA      calc_alma(series, long period=9, double offset...
ATR                        calc_atr(prices, long period=14)
AVGPRICE                              calc_avgprice(prices)
...                                                     ...
TSF         calc_tsf(series, long period=20, long offset=0)
TYPPRICE                              calc_typprice(prices)
UPDOWN    calc_updown(series, double up_level=0.0, doubl...
WCLPRICE                              calc_wclprice(prices)
WMA                           calc_wma(series, long period)

[63 rows x 1 columns]

In [5]:
from mintalib import indicators

dir(indicators)

['ABS',
 'ADX',
 'ALMA',
 'ATR',
 'AVGPRICE',
 'BBANDS',
 'BBP',
 'BBW',
 'BOP',
 'CCI',
 'CLAG',
 'CMF',
 'CROSSOVER',
 'CROSSUNDER',
 'CURVE',
 'DEMA',
 'DIFF',
 'DMI',
 'EMA',
 'EVAL',
 'EXP',
 'FLAG',
 'HMA',
 'KAMA',
 'KELTNER',
 'KER',
 'LAG',
 'LOG',
 'LROC',
 'MACD',
 'MACDV',
 'MAD',
 'MAV',
 'MAX',
 'MDI',
 'MFI',
 'MIDPRICE',
 'MIN',
 'NATR',
 'PDI',
 'PPO',
 'PRICE',
 'QSF',
 'RMA',
 'ROC',
 'RSI',
 'RVALUE',
 'SAR',
 'SIGN',
 'SLOPE',
 'SMA',
 'STDEV',
 'STEP',
 'STOCH',
 'STREAK',
 'SUM',
 'TEMA',
 'TRANGE',
 'TSF',
 'TYPPRICE',
 'UPDOWN',
 'WCLPRICE',
 'WMA',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'core',
 'wrap_indicator']

In [6]:
get_info(indicators.EMA)

{'Name': 'EMA',
 'Description': 'calc_ema(series, long period, *, bool adjust=False)'}

In [7]:
indicators.EMA.__name__

'EMA'

In [8]:




indicators = list_indicators()
indicators

                                                Description
Name
ABS                                        calc_abs(series)
ADX                        calc_adx(prices, long period=14)
ALMA      calc_alma(series, long period=9, double offset...
ATR                        calc_atr(prices, long period=14)
AVGPRICE                              calc_avgprice(prices)
...                                                     ...
TSF         calc_tsf(series, long period=20, long offset=0)
TYPPRICE                              calc_typprice(prices)
UPDOWN    calc_updown(series, double up_level=0.0, doubl...
WCLPRICE                              calc_wclprice(prices)
WMA                           calc_wma(series, long period)

[63 rows x 1 columns]

In [9]:
def backup_readme(verbose=True):
    readme = ROOTDIR.joinpath("README.md")
    if ROOTDIR.joinpath("archive").exists():
        backup = ROOTDIR.joinpath("archive/README.bak")
    else:
        backup = ROOTDIR.joinpath("README.bak")

    if verbose:
        print(f"Backing up {readme.name} ...")

    shutil.copy(readme, backup)


backup_readme()

Backing up README.md ...

In [10]:
def update_readme(verbose=True):
    title = "## List of Indicators\n"
    table = list_indicators().to_markdown()
    repl = title + "\n" + table + "\n\n\n"

    # flags m=multiline, s=dotall
    pattern = r"(?ms)(^[#]+ List of (Functions|Indicators)\n[^#]+)"

    readme = ROOTDIR.joinpath("README.md")
    contents = readme.read_text()

    output, count = re.subn(pattern, repl, contents)

    if count != 1:
        raise RuntimeError("Cound not locate list of funtions")

    if verbose:
        print(f"Updating {readme.name} ...")

    return readme.write_text(output)


update_readme()

Updating README.md ...

10416

In [11]:
def process_readme(file, *, project_url=None, branch="main", verbose=True):
    """translate relative urls to full urls"""

    if project_url is None:
        project_url = get_project_url()

    def replace(m):
        exclam, alt, url = m.groups()
        ftype = "raw" if exclam else "blob"
        if url.startswith("/"):
            url = url.removeprefix("/")
            url = posixpath.join(project_url, ftype, branch, url)
            text = f"{exclam}[{alt}]({url})"
            if verbose:
                print("mapping", m.group(0), "->", text)
        else:
            text = m.group(0)
        return text

    source = file.read_text()

    result = re.sub(
        r"(\!?) \[ ([^]]*) \] \( ([^)]+) \)", replace, source,
        flags = re.VERBOSE
        )

    return result

In [12]:
README = ROOTDIR.joinpath("README.md").resolve(strict=True)
OUTDIR = ROOTDIR / "output"
OUTDIR.mkdir(exist_ok=True)

output = process_readme(README, verbose=True)

outfile = OUTDIR.joinpath("pypi-readme.md").resolve()

print(f"Updating {outfile.name} ...")

outfile.write_text(output)

Updating pypi-readme.md ...

10416